### ISSUE TITLE
Feedback for "Connecting to External Systems"

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-business-application-studio#20]
https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/7e49887e6fd34182bebeca5a6841a0cc.html

I don't understand the note at the end of the page. When my Cloud Connector is connected to the Subaccount where I run BAS from, why would the Cloud Connector need to be connected to the SAP Business Application Studio connectivity service host? How would I connect the Cloud Connector to BAS other than via the Subaccount?

**Comment by ShiraManas** [comment]
Thanks for your feedback! I am following up with my dev teams about this issue.

**Comment by sebastianesch** [comment]
The SAP Cloud SDK has some pretty detailed documentation about this topic: https://sap.github.io/cloud-sdk/docs/js/guides/bas-external-system

**Comment by ShiraManas** [comment]
You are right about this Note. It is confusing. We have decided to remove it from this topic and leave the information in [Guided Answers](https://ga.support.sap.com/dtp/viewer/index.html#/tree/2827/actions/41344:41346:41592) only, since this information is used for troubleshooting in an extreme situation.

**Comment by sebastianesch** [comment]
My SAP Community ID is sebastian.esch.

Kind regards,
Sebastian
